### ISSUE TITLE
Error: Cannot find module 'safe-buffer'

### ISSUE THREAD

**Issue by klein0r** [herrJones/node-comfoairq#1]
Please add `safe-buffer` to dependencies

**Comment by herrJones** [comment]
Voila,

Changed the package.json to include all dependencies.
Please verify if you still have this kind of issues with the package.
I have a sh#tload of dependencies already installed so I never thought about this one

Kind regards,

   Jan

**Comment by klein0r** [comment]
Thanks a lot 👍
