### ISSUE TITLE
Duplicate bracket in log line

### ISSUE THREAD

**Issue by jensrohloff** [herrJones/node-comfoairq#7]
Hallo Herr Jones,

the double bracket is cause some issue with the iobroker adapter from klein0r

https://github.com/klein0r/ioBroker.comfoairq/issues/6

this works for me.

`console.log('** starting reconnection -> ' + config.getTimestamp()); `

https://github.com/herrJones/node-comfoairq/blob/db9187ce908782469383b19431480a2e7a6df470/lib/comfoconnect.js#L192

**Comment by herrJones** [comment]
hmm, that's a really stupid one gotten in there.
Thanks for pointing that out
